[versions]
kotlin = "1.5.0"
kotlinx-coroutines = "1.4.3"
kotlinx-serialization = "1.2.0"
ktor = "1.5.4"
slf4j = "1.6.1"

[libraries]
androidx-annotation = { group = "androidx.annotation", name = "annotation", version = "1.2.0" }
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.3.2" }
clikt = { group = "com.github.ajalt.clikt", name = "clikt", version = "3.1.0" }
kasechange = { group = "net.pearx.kasechange", name = "kasechange", version = "1.3.0" }
koin = { group = "io.insert-koin", name = "koin-core", version = "2.2.2" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
kotlinPoet = { group = "com.squareup", name = "kotlinpoet", version = "1.8.0" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-http = { group = "io.ktor", name = "ktor-http", version.ref = "ktor" }
ktor-io = { group = "io.ktor", name = "ktor-io", version.ref = "ktor" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization = { group = "io.ktor", name = "ktor-client-serialization-jvm", version.ref = "ktor" }
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
swaggerParser = { group = "io.swagger.parser.v3", name = "swagger-parser", version = "2.0.25" }
