[versions]
android-gradle = "8.13.2"
android-sdk = "36"
animalsniffer = "2.0.1"
binarycompatibilityvalidator = "0.18.1"
clikt = "5.0.3"
detekt = "1.23.8"
dokka = "2.1.0"
download = "5.6.0"
foojay-resolver = "1.0.0"
gummybears = "0.12.0"
kasechange = "1.4.1"
koin = "4.1.1"
kotest = "6.0.7"
kotlin = "2.2.10"
ksp = "2.3.4"
kotlin-logging = "7.0.13"
kotlinpoet = "2.2.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.9.0"
nexuspublish = "2.0.0"
okhttp = "5.3.2"
slf4j = "2.0.17"
swagger-parser = "2.1.37"

[plugins]
android-library = { id = "com.android.library", version.ref = "android-gradle" }
animalsniffer = { id = "ru.vyarus.animalsniffer", version.ref = "animalsniffer" }
binarycompatibilityvalidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binarycompatibilityvalidator" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
download = { id = "de.undercouch.download", version.ref = "download" }
foojay-resolver = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver" }
kotest = { id = "io.kotest", version.ref = "kotest" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
nexuspublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexuspublish" }

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
gummybears-api19 = { module = "com.toasttab.android:gummy-bears-api-19", version.ref = "gummybears" }
kasechange = { module = "net.pearx.kasechange:kasechange", version.ref = "kasechange" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version.ref = "swagger-parser" }
