[versions]
android-gradle = "7.2.2"
androidx-annotation = "1.5.0"
androidx-core = "1.9.0"
binarycompatibilityvalidator = "0.11.1"
clikt = "3.5.0"
detekt = "1.21.0"
dokka = "1.7.10"
download = "5.2.1"
kasechange = "1.3.0"
koin = "3.2.2"
kotest = "5.4.2"
kotlin = "1.7.10"
kotlin-logging = "3.0.0"
kotlinpoet = "1.12.0"
kotlinx-coroutines = "1.6.4"
kotlinx-serialization = "1.4.0"
ktor = "1.6.8"
nexuspublish = "1.1.0"
slf4j = "2.0.3"
swagger-parser = "2.1.3"

[plugins]
binarycompatibilityvalidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binarycompatibilityvalidator" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
download = { id = "de.undercouch.download", version.ref = "download" }
kotest = { id = "io.kotest.multiplatform", version.ref = "kotest" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
nexuspublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexuspublish" }

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
kasechange = { module = "net.pearx.kasechange:kasechange", version.ref = "kasechange" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-logging = { module = "io.github.microutils:kotlin-logging", version.ref = "kotlin-logging" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-http = { module = "io.ktor:ktor-http", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version.ref = "swagger-parser" }
