name: SDK / Update OpenAPI

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  api-spec-update:
    name: Update
    runs-on: ubuntu-24.04
    if: ${{ contains(github.repository_owner, 'jellyfin') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
      - name: Set STABLE_API_VERSION
        run: |
          VERSION=$(curl -sL https://repo.jellyfin.org/releases/openapi/jellyfin-openapi-stable.json | jq -r .info.version)
          echo "STABLE_API_VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Update api spec
        run: |
          ./gradlew :openapi-generator:updateApiSpecStable
          ./gradlew apiDump
      - name: Create pull request
        if: always()
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        with:
          token: ${{ secrets.JF_BOT_TOKEN }}
          commit-message: 'Update generated sources to ${{ env.STABLE_API_VERSION }}'
          committer: 'jellyfin-bot <team@jellyfin.org>'
          author: 'jellyfin-bot <team@jellyfin.org>'
          title: 'Update OpenAPI to ${{ env.STABLE_API_VERSION }}'
          labels: |
            dependencies
            openapi
          branch: 'openapi-update-'
          branch-suffix: 'short-commit-hash'
          delete-branch: true
          body: 'Update OpenAPI to ${{ env.STABLE_API_VERSION }}'
