name: SDK / Update OpenAPI

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  api-spec-update:
    name: Update
    runs-on: ubuntu-24.04
    if: ${{ contains(github.repository_owner, 'jellyfin') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Setup Java
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
      - name: Set STABLE_API_VERSION
        run: |
          VERSION=$(curl -sL https://repo.jellyfin.org/releases/openapi/jellyfin-openapi-stable.json | jq -r .info.version)
          echo "STABLE_API_VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Update api spec
        run: |
          ./gradlew :openapi-generator:updateApiSpecStable
          ./gradlew apiDump
      - name: Create pull request
        if: always()
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        with:
          token: ${{ secrets.JF_BOT_TOKEN }}
          commit-message: 'Update generated sources to ${{ env.STABLE_API_VERSION }}'
          committer: 'jellyfin-bot <team@jellyfin.org>'
          author: 'jellyfin-bot <team@jellyfin.org>'
          title: 'Update OpenAPI to ${{ env.STABLE_API_VERSION }}'
          labels: |
            dependencies
            openapi
          branch: 'openapi-update-'
          branch-suffix: 'short-commit-hash'
          delete-branch: true
          body: 'Update OpenAPI to ${{ env.STABLE_API_VERSION }}'
