name: SDK / Update OpenAPI

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  api-spec-update:
    name: Update
    runs-on: ubuntu-22.04
    if: ${{ contains(github.repository_owner, 'jellyfin') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Setup Java
        uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f # v2
      - name: Set STABLE_API_VERSION
        run: |
          VERSION=$(curl -sL https://repo.jellyfin.org/releases/openapi/jellyfin-openapi-stable.json | jq -r .info.version)
          echo "STABLE_API_VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Update api spec
        run: |
          ./gradlew :openapi-generator:updateApiSpecStable
          ./gradlew apiDump
      - name: Set AFFECTED_FILES and AFFECTED_FILES_COUNT variables
        run: |
          AFFECTED_FILES=$(git status --porcelain)
          echo "AFFECTED_FILES=${AFFECTED_FILES}" >> $GITHUB_ENV
          echo "AFFECTED_FILES_COUNT=$(echo ${AFFECTED_FILES} | wc -l | xargs)" >> $GITHUB_ENV
      - name: Create pull request
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4
        with:
          token: ${{ secrets.JF_BOT_TOKEN }}
          commit-message: 'Update generated sources to ${{ env.STABLE_API_VERSION }}'
          committer: 'jellyfin-bot <team@jellyfin.org>'
          author: 'jellyfin-bot <team@jellyfin.org>'
          title: 'Update OpenAPI to ${{ env.STABLE_API_VERSION }}'
          labels: |
            dependencies
            openapi
          branch: 'openapi-update-'
          branch-suffix: 'short-commit-hash'
          delete-branch: true
          body: |
            ## Changed files
            <details>
              <summary>Changed ${{ env.AFFECTED_FILES_COUNT }} files</summary>
              ${{ env.AFFECTED_FILES }}
            </details>
